package com.jary.naruto.map.dao;

import com.jary.framework.core.dao.BaseMapper;
import com.jary.naruto.map.model.Location;
import com.jary.naruto.map.model.LocationExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LocationMapper extends BaseMapper<Location, String> {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_location
	 * @mbggenerated
	 */
	int countByExample(LocationExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_location
	 * @mbggenerated
	 */
	int deleteByExample(LocationExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_location
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(String locationId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_location
	 * @mbggenerated
	 */
	int insert(Location record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_location
	 * @mbggenerated
	 */
	int insertSelective(Location record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_location
	 * @mbggenerated
	 */
	List<Location> selectByExample(LocationExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_location
	 * @mbggenerated
	 */
	Location selectByPrimaryKey(String locationId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_location
	 * @mbggenerated
	 */
	int updateByExampleSelective(@Param("record") Location record, @Param("example") LocationExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_location
	 * @mbggenerated
	 */
	int updateByExample(@Param("record") Location record, @Param("example") LocationExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_location
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(Location record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_location
	 * @mbggenerated
	 */
	int updateByPrimaryKey(Location record);

	List<Location> selectByRelaId(@Param("relaId") String relaId);
}