package com.jary.naruto.sys.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.jary.framework.core.dao.BaseMapper;
import com.jary.naruto.sys.model.Permission;
import com.jary.naruto.sys.model.PermissionExample;

public interface PermissionMapper extends BaseMapper<Permission, String> {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_permission
	 * @mbggenerated
	 */
	int countByExample(PermissionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_permission
	 * @mbggenerated
	 */
	int deleteByExample(PermissionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_permission
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(String permissionId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_permission
	 * @mbggenerated
	 */
	int insert(Permission record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_permission
	 * @mbggenerated
	 */
	int insertSelective(Permission record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_permission
	 * @mbggenerated
	 */
	List<Permission> selectByExample(PermissionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_permission
	 * @mbggenerated
	 */
	Permission selectByPrimaryKey(String permissionId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_permission
	 * @mbggenerated
	 */
	int updateByExampleSelective(@Param("record") Permission record,
			@Param("example") PermissionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_permission
	 * @mbggenerated
	 */
	int updateByExample(@Param("record") Permission record,
			@Param("example") PermissionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_permission
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(Permission record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_permission
	 * @mbggenerated
	 */
	int updateByPrimaryKey(Permission record);

	/**
	 * @param userId
	 * @return
	 */
	List<Permission> getByUserId(String userId);
}