package com.jary.naruto.sys.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.jary.framework.core.dao.BaseMapper;
import com.jary.naruto.sys.model.UserRole;
import com.jary.naruto.sys.model.UserRoleExample;

public interface UserRoleMapper extends BaseMapper<UserRole, String> {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user_role
	 * @mbggenerated
	 */
	int countByExample(UserRoleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user_role
	 * @mbggenerated
	 */
	int deleteByExample(UserRoleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user_role
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(String userRoleId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user_role
	 * @mbggenerated
	 */
	int insert(UserRole record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user_role
	 * @mbggenerated
	 */
	int insertSelective(UserRole record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user_role
	 * @mbggenerated
	 */
	List<UserRole> selectByExample(UserRoleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user_role
	 * @mbggenerated
	 */
	UserRole selectByPrimaryKey(String userRoleId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user_role
	 * @mbggenerated
	 */
	int updateByExampleSelective(@Param("record") UserRole record,
			@Param("example") UserRoleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user_role
	 * @mbggenerated
	 */
	int updateByExample(@Param("record") UserRole record,
			@Param("example") UserRoleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user_role
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(UserRole record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user_role
	 * @mbggenerated
	 */
	int updateByPrimaryKey(UserRole record);
}