package com.jary.naruto.map.model;

import com.jary.framework.core.entity.BaseEntity;

public class LocationRelation extends BaseEntity {
    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column r_location.r_id
     *
     * @mbggenerated
     */
    private String rId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column r_location.location_id
     *
     * @mbggenerated
     */
    private String locationId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column r_location.rela_id
     *
     * @mbggenerated
     */
    private String relaId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column r_location.status
     *
     * @mbggenerated
     */
    private Integer status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column r_location.r_id
     *
     * @return the value of r_location.r_id
     *
     * @mbggenerated
     */
    public String getrId() {
        return rId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column r_location.r_id
     *
     * @param rId the value for r_location.r_id
     *
     * @mbggenerated
     */
    public void setrId(String rId) {
        this.rId = rId == null ? null : rId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column r_location.location_id
     *
     * @return the value of r_location.location_id
     *
     * @mbggenerated
     */
    public String getLocationId() {
        return locationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column r_location.location_id
     *
     * @param locationId the value for r_location.location_id
     *
     * @mbggenerated
     */
    public void setLocationId(String locationId) {
        this.locationId = locationId == null ? null : locationId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column r_location.rela_id
     *
     * @return the value of r_location.rela_id
     *
     * @mbggenerated
     */
    public String getRelaId() {
        return relaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column r_location.rela_id
     *
     * @param relaId the value for r_location.rela_id
     *
     * @mbggenerated
     */
    public void setRelaId(String relaId) {
        this.relaId = relaId == null ? null : relaId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column r_location.status
     *
     * @return the value of r_location.status
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column r_location.status
     *
     * @param status the value for r_location.status
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

	@Override
	public Object getId() {
		return rId;
	}
}