package com.jary.naruto.map.model;

import com.alibaba.fastjson.annotation.JSONField;
import com.jary.framework.core.entity.BaseEntity;
import java.util.Date;

import org.springframework.format.annotation.DateTimeFormat;

public class Location extends BaseEntity {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_location.location_id
	 * @mbggenerated
	 */
	private String locationId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_location.name
	 * @mbggenerated
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_location.description
	 * @mbggenerated
	 */
	private String description;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_location.longitude
	 * @mbggenerated
	 */
	private Double longitude;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_location.latitude
	 * @mbggenerated
	 */
	private Double latitude;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_location.create_time
	 * @mbggenerated
	 */
    @DateTimeFormat(pattern="yyyy-MM-dd HH:mm:ss")
    @JSONField(format="yyyy-MM-dd HH:mm:ss")
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_location.status
	 * @mbggenerated
	 */
	private Integer status;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_location.location_id
	 * @return  the value of t_location.location_id
	 * @mbggenerated
	 */
	public String getLocationId() {
		return locationId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_location.location_id
	 * @param locationId  the value for t_location.location_id
	 * @mbggenerated
	 */
	public void setLocationId(String locationId) {
		this.locationId = locationId == null ? null : locationId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_location.name
	 * @return  the value of t_location.name
	 * @mbggenerated
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_location.name
	 * @param name  the value for t_location.name
	 * @mbggenerated
	 */
	public void setName(String name) {
		this.name = name == null ? null : name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_location.description
	 * @return  the value of t_location.description
	 * @mbggenerated
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_location.description
	 * @param description  the value for t_location.description
	 * @mbggenerated
	 */
	public void setDescription(String description) {
		this.description = description == null ? null : description.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_location.longitude
	 * @return  the value of t_location.longitude
	 * @mbggenerated
	 */
	public Double getLongitude() {
		return longitude;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_location.longitude
	 * @param longitude  the value for t_location.longitude
	 * @mbggenerated
	 */
	public void setLongitude(Double longitude) {
		this.longitude = longitude;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_location.latitude
	 * @return  the value of t_location.latitude
	 * @mbggenerated
	 */
	public Double getLatitude() {
		return latitude;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_location.latitude
	 * @param latitude  the value for t_location.latitude
	 * @mbggenerated
	 */
	public void setLatitude(Double latitude) {
		this.latitude = latitude;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_location.create_time
	 * @return  the value of t_location.create_time
	 * @mbggenerated
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_location.create_time
	 * @param createTime  the value for t_location.create_time
	 * @mbggenerated
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_location.status
	 * @return  the value of t_location.status
	 * @mbggenerated
	 */
	public Integer getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_location.status
	 * @param status  the value for t_location.status
	 * @mbggenerated
	 */
	public void setStatus(Integer status) {
		this.status = status;
	}

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	@Override
	public Object getId() {
		return locationId;
	}
}