package com.jary.naruto.sys.model;

import com.jary.framework.core.entity.BaseEntity;

public class Permission extends BaseEntity {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_permission.permission_id
	 * @mbggenerated
	 */
	private String permissionId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_permission.token
	 * @mbggenerated
	 */
	private String token;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_permission.url
	 * @mbggenerated
	 */
	private String url;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_permission.description
	 * @mbggenerated
	 */
	private String description;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_permission.role_id
	 * @mbggenerated
	 */
	private String roleId;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_permission.permission_id
	 * @return  the value of t_permission.permission_id
	 * @mbggenerated
	 */
	public String getPermissionId() {
		return permissionId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_permission.permission_id
	 * @param permissionId  the value for t_permission.permission_id
	 * @mbggenerated
	 */
	public void setPermissionId(String permissionId) {
		this.permissionId = permissionId == null ? null : permissionId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_permission.token
	 * @return  the value of t_permission.token
	 * @mbggenerated
	 */
	public String getToken() {
		return token;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_permission.token
	 * @param token  the value for t_permission.token
	 * @mbggenerated
	 */
	public void setToken(String token) {
		this.token = token == null ? null : token.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_permission.url
	 * @return  the value of t_permission.url
	 * @mbggenerated
	 */
	public String getUrl() {
		return url;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_permission.url
	 * @param url  the value for t_permission.url
	 * @mbggenerated
	 */
	public void setUrl(String url) {
		this.url = url == null ? null : url.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_permission.description
	 * @return  the value of t_permission.description
	 * @mbggenerated
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_permission.description
	 * @param description  the value for t_permission.description
	 * @mbggenerated
	 */
	public void setDescription(String description) {
		this.description = description == null ? null : description.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_permission.role_id
	 * @return  the value of t_permission.role_id
	 * @mbggenerated
	 */
	public String getRoleId() {
		return roleId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_permission.role_id
	 * @param roleId  the value for t_permission.role_id
	 * @mbggenerated
	 */
	public void setRoleId(String roleId) {
		this.roleId = roleId == null ? null : roleId.trim();
	}

	/* (non-Javadoc)
	 * @see com.jary.test.springmvc.common.model.BaseEntity#getId()
	 */
	@Override
	public Object getId() {
		return this.permissionId;
	}
}