package com.jary.naruto.sys.model;

import java.util.List;

import com.jary.framework.core.entity.BaseEntity;

public class Role extends BaseEntity {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_role.role_id
	 * @mbggenerated
	 */
	private String roleId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_role.name
	 * @mbggenerated
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_role.description
	 * @mbggenerated
	 */
	private String description;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_role.status
	 * @mbggenerated
	 */
	private String status;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_role.role_id
	 * @return  the value of t_role.role_id
	 * @mbggenerated
	 */
	public String getRoleId() {
		return roleId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_role.role_id
	 * @param roleId  the value for t_role.role_id
	 * @mbggenerated
	 */
	public void setRoleId(String roleId) {
		this.roleId = roleId == null ? null : roleId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_role.name
	 * @return  the value of t_role.name
	 * @mbggenerated
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_role.name
	 * @param name  the value for t_role.name
	 * @mbggenerated
	 */
	public void setName(String name) {
		this.name = name == null ? null : name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_role.description
	 * @return  the value of t_role.description
	 * @mbggenerated
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_role.description
	 * @param description  the value for t_role.description
	 * @mbggenerated
	 */
	public void setDescription(String description) {
		this.description = description == null ? null : description.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_role.status
	 * @return  the value of t_role.status
	 * @mbggenerated
	 */
	public String getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_role.status
	 * @param status  the value for t_role.status
	 * @mbggenerated
	 */
	public void setStatus(String status) {
		this.status = status == null ? null : status.trim();
	}

	/* (non-Javadoc)
	 * @see com.jary.test.springmvc.common.model.BaseEntity#getId()
	 */
	@Override
	public Object getId() {
		return this.roleId;
	}

	/**
	 * @return
	 */
	public List<Permission> getPermissionList() {
		// TODO Auto-generated method stub
		return null;
	}
}