package com.jary.naruto.sys.model;

import com.jary.framework.core.entity.BaseEntity;

public class UserRole extends BaseEntity {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_user_role.user_role_id
	 * @mbggenerated
	 */
	private String userRoleId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_user_role.role_id
	 * @mbggenerated
	 */
	private String roleId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_user_role.user_id
	 * @mbggenerated
	 */
	private String userId;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_user_role.user_role_id
	 * @return  the value of t_user_role.user_role_id
	 * @mbggenerated
	 */
	public String getUserRoleId() {
		return userRoleId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_user_role.user_role_id
	 * @param userRoleId  the value for t_user_role.user_role_id
	 * @mbggenerated
	 */
	public void setUserRoleId(String userRoleId) {
		this.userRoleId = userRoleId == null ? null : userRoleId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_user_role.role_id
	 * @return  the value of t_user_role.role_id
	 * @mbggenerated
	 */
	public String getRoleId() {
		return roleId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_user_role.role_id
	 * @param roleId  the value for t_user_role.role_id
	 * @mbggenerated
	 */
	public void setRoleId(String roleId) {
		this.roleId = roleId == null ? null : roleId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_user_role.user_id
	 * @return  the value of t_user_role.user_id
	 * @mbggenerated
	 */
	public String getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_user_role.user_id
	 * @param userId  the value for t_user_role.user_id
	 * @mbggenerated
	 */
	public void setUserId(String userId) {
		this.userId = userId == null ? null : userId.trim();
	}

	/* (non-Javadoc)
	 * @see com.jary.test.springmvc.common.model.BaseEntity#getId()
	 */
	@Override
	public Object getId() {
		return this.userRoleId;
	}
}